version: "3.8"

services:
  db:
    image: postgres:15-alpine
    env_file: ".env"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  login_server:
    build: .
    depends_on:
      - db
    env_file: ".env"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      bash -lc "
      # wait for Postgres to be ready
      until pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT}; do
        echo 'Waiting for database...'
        sleep 1
      alembic upgrade head &&
      python -m login_server
      "
    
volumes:
  db-data:
