version: "3.8"

services:
  db:
    image: postgres:15-alpine
    env_file: ".env"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  login_server:
    build: .
    depends_on:
      - db
    env_file: ".env"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    
volumes:
  db-data:
