version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: login_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: login_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  login_server:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: login_user
      DB_PASSWORD: password
      DB_NAME: login_db
    command: python -m login_server
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  db-data:

